//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.26 at 11:38:49 AM GMT 
//


package eu.fiware.iot.ngsi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Association complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Association">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceEntityId" type="{}EntityId" minOccurs="0"/>
 *         &lt;element name="targetEntityId" type="{}EntityId" minOccurs="0"/>
 *         &lt;element name="attributeAssociationList" type="{}AttributeAssociationList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Association", propOrder = {
    "sourceEntityId",
    "targetEntityId",
    "attributeAssociationList"
})
public class Association {

    protected EntityId sourceEntityId;
    protected EntityId targetEntityId;
    protected AttributeAssociationList attributeAssociationList;

    /**
     * Gets the value of the sourceEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link EntityId }
     *     
     */
    public EntityId getSourceEntityId() {
        return sourceEntityId;
    }

    /**
     * Sets the value of the sourceEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityId }
     *     
     */
    public void setSourceEntityId(EntityId value) {
        this.sourceEntityId = value;
    }

    /**
     * Gets the value of the targetEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link EntityId }
     *     
     */
    public EntityId getTargetEntityId() {
        return targetEntityId;
    }

    /**
     * Sets the value of the targetEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityId }
     *     
     */
    public void setTargetEntityId(EntityId value) {
        this.targetEntityId = value;
    }

    /**
     * Gets the value of the attributeAssociationList property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeAssociationList }
     *     
     */
    public AttributeAssociationList getAttributeAssociationList() {
        return attributeAssociationList;
    }

    /**
     * Sets the value of the attributeAssociationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeAssociationList }
     *     
     */
    public void setAttributeAssociationList(AttributeAssociationList value) {
        this.attributeAssociationList = value;
    }

}
