//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:29:07 PM GMT 
//


package eu.fiware.iot.ngsi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContextRegistration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContextRegistration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entityIdList" type="{}EntityIdList" minOccurs="0"/>
 *         &lt;element name="contextRegistrationAttributeList" type="{}ContextRegistrationAttributeList" minOccurs="0"/>
 *         &lt;element name="registrationMetadata" type="{}RegistrationMetadata" minOccurs="0"/>
 *         &lt;element name="providingApplication" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContextRegistration", propOrder = {
    "entityIdList",
    "contextRegistrationAttributeList",
    "registrationMetadata",
    "providingApplication"
})
public class ContextRegistration {

    protected EntityIdList entityIdList;
    protected ContextRegistrationAttributeList contextRegistrationAttributeList;
    protected RegistrationMetadata registrationMetadata;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String providingApplication;

    /**
     * Gets the value of the entityIdList property.
     * 
     * @return
     *     possible object is
     *     {@link EntityIdList }
     *     
     */
    public EntityIdList getEntityIdList() {
        return entityIdList;
    }

    /**
     * Sets the value of the entityIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityIdList }
     *     
     */
    public void setEntityIdList(EntityIdList value) {
        this.entityIdList = value;
    }

    /**
     * Gets the value of the contextRegistrationAttributeList property.
     * 
     * @return
     *     possible object is
     *     {@link ContextRegistrationAttributeList }
     *     
     */
    public ContextRegistrationAttributeList getContextRegistrationAttributeList() {
        return contextRegistrationAttributeList;
    }

    /**
     * Sets the value of the contextRegistrationAttributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextRegistrationAttributeList }
     *     
     */
    public void setContextRegistrationAttributeList(ContextRegistrationAttributeList value) {
        this.contextRegistrationAttributeList = value;
    }

    /**
     * Gets the value of the registrationMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationMetadata }
     *     
     */
    public RegistrationMetadata getRegistrationMetadata() {
        return registrationMetadata;
    }

    /**
     * Sets the value of the registrationMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationMetadata }
     *     
     */
    public void setRegistrationMetadata(RegistrationMetadata value) {
        this.registrationMetadata = value;
    }

    /**
     * Gets the value of the providingApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvidingApplication() {
        return providingApplication;
    }

    /**
     * Sets the value of the providingApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvidingApplication(String value) {
        this.providingApplication = value;
    }

}
